// This file is automatically generated.
// Please do not change this file!
interface ICssExports {
  'header': string;
  'headerBg': string;
  'header_bg': string;
}
export const cssExports: ICssExports;
export default cssExports;
